### ISSUE TITLE
URN and UUID

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#69]
Update proposal for BIDS Prov (BEP028)

### Problem Statement
On the [BIDS-Prov meeting (November 8, 2021)](https://docs.google.com/document/d/1Z2CCum9vqxRenTElhgv1l1H9gt1BGwkvT8mGWKtX4Rk/edit), we agreed to include the following in BIDS-Prov:

 - For UUIDs that we can resolve : we'll use a specific prefix (similar to e.g. `dandiasset` for DANDI)
 - For UUIDs that we cannot resolve from any service in any way : use an `urn` prefix

Looking more closely at `urn`, it looks like those have to be accompagnied by a registered namespace identifier, cf. https://en.wikipedia.org/wiki/Uniform_Resource_Name. 

We could directly reuse the already registered UUID namespace identifier, e.g. "urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66"

@satra: can you confirm that the latter (i.e. using `urn:uuid`) is what you had in mind)? 

Once we have converged on this, TODO:
 - [ ] Update the spec and examples to replace all instances of "niiri:" with "urn:uuid:"
 - [ ] Add a section in the BIDS-Prov spec explaining how identifiers are chosen (two options as described above)

**Comment by satra** [comment]
@cmaumet - indeed that's what i had in mind. but recently someone pointed me to using `ark` as a resolver, so that may be something to consider. there is no guarantee of resolution but ark would like purl provide an option to resolving. it can still be a uuid, but it would look instead like `ark:<prefix>:<uuid>`. 

people can still use a different uri for resolving but we could consider whether `ark` (run by the california libraries), would be a good choice instead of the `urn`, just in case a user does want to provide a resolution endpoint for the uuid.
